use_frameworks!
platform :ios, '9.0'

target 'Khalti_Example' do
    
  pod 'IQKeyboardManager'
  pod 'Khalti'  , :path => '../'

  target 'Khalti_Tests' do
    inherit! :search_paths
    
    
  end
end
